### ISSUE TITLE
Visibility of shared attitude in trade

### ISSUE THREAD

**Issue by DanielBadura** [LaughingLeader-DOS2-Mods/BarteringTweaks#1]
Hi :)
first thanks for this awesome mod!

Is it possible to see the "real" attitude towards the trader? When i'm trading the discounts are calculated correctly for example max attitude but the score in the trade menu is at 40.

**Comment by LaughingLeader** [comment]
Unfortunately that's a bug with the trading screen UI not updating values after the trade has opened. You can "refresh" the displayed amount by switching between characters.

**Comment by DanielBadura** [comment]
Couldnt be a workaround to change the attitude as soon as the character start to talk with the npc?
Then the value should be already changed and the trade ui has the correct value, right?

**Comment by LaughingLeader** [comment]
Possibly, but that may open up other issues if that dialog can modify attitude. If it's already maxed and  dialog gives additional attitude, that amount won't be recorded, as attitude changing events don't trigger if you're at max attitude already.

Additionally, if you have persuasion and attitude sharing enabled, the persuasion bonus is disabled in trade, so attitude can be calculated correctly and the appropriate amount can be removed (persuasion gives you +5 attitude per point, so we remove this when determining the max attitude to share, then re-apply persuasion sharing when trade ends). Calculating attitude to share when persuasion bonuses are active can cause issues (even if you include persuason * 5 in the calculations), so clearing that when trading with attitude sharing is the simplest solution.

By "switching characters" in the trade screen, I mean literally clicking on another portrait, and then clicking back. F2 + F1 for a quick shortcut. That's enough to make the UI show the correct value, so personally I consider this a non-issue, since the discount is definitely applied either way.

**Comment by DanielBadura** [comment]
We are playing as a 4 man party so switching characters is not possible in our case.

I dont get the part with the attitude and persuasion calculation problems in a talk, isnt it the same when trading?

**Comment by LaughingLeader** [comment]
Frankly, getting the real amount of attitude to add/remove is a huge pain.

Shared persuasion messes with the attitude amounts when querying the character's attitude to a trader, and Stench can modify this amount as well (-25 active and max). When adding the shared attitude, I have to then check the actual result to see what to subtract when removing the shared values. Then when you add on top of that attitude adjustments from giving items/gold, angering the trader, dialog changing attitude, etc., there's a lot of pitfalls where things can go wrong.

It's been a while since I've dealt with that problem, but I can take a look again. Just know that you're asking for me to open up a can of worms again, haha.

**Comment by LaughingLeader** [comment]
Little update - After several hours, I finally remember why attitude sharing in dialog is a pain. Stench in combination with shared persuasion bonuses makes it hard to determine the real amount of attitude to share when you begin mixing in multiple active dialogs, both for singleplayer and multiplayer. Juggling persuasion bonuses and determining the real value of attitude shared when also checking for stench caps and trying to maintain sharing among multiple dialogs gets a bit silly. 

Instead, I opted for a simpler solution: Rather than try to determine actual attitude, balance attitude amounts and remove the bonuses when dialog ends, attitude bonuses will simply be shared across party members. For instance, if you gift some gold to an NPC and get +50 attitude to bring you up to 70, everyone will be brought up to 70 attitude.

Way easier to deal with in the long run, and that should reduce some scripting overhead since now attitude sharing only runs when attitude changes positively, rather than every time dialog starts.

For multiplayer, your friends will get +Attitude any time someone gains attitude with an NPC, and by the time they go into the trade menu, that attitude will be there and will be visible.

**Comment by DanielBadura** [comment]
Wow, nice thanks man!!!
I just wanted to suggest to help you with that but you already did it. ❤️

**Comment by DanielBadura** [comment]
I came back to report my experience with the changes.

In my savegame with one other person (2 Man LoneWolf Party) its working like a charm. I played that savegame the last days.
Today i started to play with my 4 man Party again and there it doesnt work right. The whole attitude share just doesnt seem to work. Persuasion and Batering works as normal but no attitude sharing.

I will upload some screens with the debug messages on. 

![sharing](https://user-images.githubusercontent.com/2017762/51491233-fb0d2080-1dad-11e9-8ecb-8600a1249a28.png)
![sharing_settings](https://user-images.githubusercontent.com/2017762/51491234-fb0d2080-1dad-11e9-9571-8ec7d3d9c12b.png)

**Comment by LaughingLeader** [comment]
Is everyone up-to-date? Does attitude sharing work locally? Remember it's shared when attitude changes now, instead of when dialog starts. There's nothing in the code that checks for User IDs or anything when sharing attitude - It simply iterates on the party and brings everybody's attitude up to the target level (if it's higher than what they have).

**Comment by DanielBadura** [comment]
I'll close this issue, i think it worked later on but i failed to responed. Thanks again for all the work you have put into these amazing mods! 💪
